# ===================================================================
# Spring Boot configuration.
#
# This configuration is used for unit/integration tests.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
  client:
    enabled: false
  instance:
    appname: bakeAnApi
    instanceId: bakeAnApi:${spring.application.instance-id:${random.value}}

mongock:
  migration-scan-package:
    - com.bakeanapi.config.dbmigrations
  mongo-db:
    read-concern: local
    write-concern:
      journal: false

spring:
  application:
    name: bakeAnApi
  cloud:
    config:
      enabled: false
  jackson:
    serialization:
      write-durations-as-timestamps: false
  mail:
    host: localhost
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages:
    basename: i18n/messages
  task:
    execution:
      thread-name-prefix: bake-an-api-task-
      pool:
        core-size: 1
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: bake-an-api-scheduling-
      pool:
        size: 20
  thymeleaf:
    mode: HTML

server:
  port: 10344
  address: localhost

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================
jhipster:
  clientApp:
    name: 'bakeAnApiApp'
  mail:
    from: bakeAnApi@localhost.com
    base-url: http://127.0.0.1:8080
  logging:
    # To test json console appender
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 (you can type `echo 'secret-key'|base64` on your command line)
        base64-secret: NThmZDFkYzRhM2MzMTNkYWI4NmM2NzBhMGNkZTliMDllZDA3NzQwODRlZGZhMTAxZjQ0N2FiY2FmMmM4NjQxZGRiZDkzY2JjZmQzNjQ0NmU1YWM2NzgyYmEyMmQyYjYzYjI2NGJjOTYxODYyNmI2ZmY4OWYwMmMzNzc3YmVhMTg=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:
management:
  health:
    mail:
      enabled: false
